SameetBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name="home"),
    path('blog/', views.blog, name="blog"),
    path('blog/article/<slug:slug>', views.details, name="details"),
    path('topics/', views.topics, name="topics"),
    path('topics/<slug:slug>', views.topic, name="topic")
]

blog/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField

# Create your models here.

class Topics(models.Model):
    title = models.CharField(verbose_name="عنوان", max_length=200)
    slug = models.SlugField(verbose_name="ادرس", max_length=200, unique=True)
    position = models.IntegerField(verbose_name="به ترتیب از ")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "تاپیک"
        verbose_name_plural = "تاپیک ها"

class Article(models.Model):
    ArticleStatus =  (
        ("P", "Published"),
        ("D", "Draft")
    )
    title = models.CharField(verbose_name="عنوان", max_length=200)
    slug = models.SlugField(verbose_name="ادرس مقاله", max_length=200, unique=True)
    topics = models.ManyToManyField(Topics, verbose_name="تاپیک", related_name="articles")
    body = HTMLField(verbose_name="محتوا", null=True, blank=True)
    thumbnail = models.ImageField(verbose_name="تصویر بند انگشتی", upload_to="images")
    published = models.DateTimeField(verbose_name="زمان انتشار", default=timezone.now)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(verbose_name="وضعیت نمایش", max_length=1, choices=ArticleStatus)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

class HomeContent(models.Model):
    title = models.CharField(verbose_name="عنوان", max_length=200, null=True, blank=True)
    body = models.TextField(verbose_name="محتوا", max_length=250, null=True, blank=True)
    thumbnail = models.ImageField(verbose_name="تصویر بند انگشتی", upload_to="images")
    thumbnail_link = models.CharField(verbose_name="لینک محتوا", max_length=300, null=True, blank=True)
    published = models.DateTimeField(verbose_name="زمان انتشار", default=timezone.now)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "محتوای صفحه ی اصلی"
        verbose_name_plural = "محتوای صفحه اصلی"

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator
from . import models

# Create your views here.
def home(request):
    ''' this is function of the blog home. '''
    context = {
        "contents": models.HomeContent.objects.all().order_by('-published'),
    }
    return render(request, 'blog/base.html', context)

def details(request, slug):
    ''' this is function of the blog details articles. '''
    context = {
        "article": get_object_or_404(models.Article, slug=slug),
        "topics": models.Topics.objects.all()
    }
    return render(request, "blog/details.html", context)

def blog(request):
    ''' this is function of the site (blog)'''
    all_article = models.Article.objects.filter(status="P").order_by('-published')
    paginator = Paginator(all_article, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "articles": page_obj,
        "topics": models.Topics.objects.all()
    }
    return render(request, "blog/blog.html", context)

def topics(request):
    ''' this is function of the article topics. '''
    context = {
        "topics": models.Topics.objects.all()
    }
    return render(request, 'blog/topics.html', context)

def topic(request, slug):
    ''' this is function of the topics. '''
    context = {
        "topic": get_object_or_404(models.Topics, slug=slug),
        "topics": models.Topics.objects.all()
    }
    return render(request, "blog/topic.html", context)

blog/templates/blog/articles.html
<div class="container">
	<div id="main">
		<h1 style="color: #d19a66; text-align: center; margin: 30px;">مقالات</h2>
		{% for article in articles %}
			<article id="article">
				<div class="card col-sm-12 col-xl-9">
					<div class="row g-0">
						<div class="article-tumbnail col-xl-4 col-lg-4 col-sm-12 ">
							<a href="{% url 'blog:details' article.slug %}"><img src="{{ article.thumbnail.url }}" class="img-fluid rounded-start" alt="..."></a>
						</div>
						<div id="card-body" class="col-sm-12 col-lg-8 col-xl-8">
							<div class="card-body">
								<a href="{% url 'blog:details' article.slug %}"><h2 class="card-title">{{ article.title }}</h2></a>
								<p>{{ article.created }}</p>
								<p>
									تاپیک :
									{% for topic in topics %}
										{{ topic.title }} , 
									{% endfor %}
								</p>
							</div>
						</div>
					</div>
				</div>
			</article>
		{% endfor %}
	</div>
  <footer id='footer'>
    {% if articles.has_next %}
      <a class="pages" href="{% url 'blog:blog' %}?page={{articles.next_page_number}}">&rarr; صفحه ی بعدی </a>
    {% endif %}
    {% if articles.has_previous %}
      <a class="pages" href="{% url 'blog:blog' %}?page={{articles.previous_page_number}}">صفحه قبلی &larr;</a>
    {% endif %}
  </footer>
</div>

blog/templates/blog/base.html
{% extends 'blog/index.html' %}

{% load static %}

{% block title %}صفحه اصلی{% endblock %}
{% block body %}
	{% block header %}{% include 'blog/header.html' %}{% endblock %}
	{% block main %}{% include 'blog/main.html' %}{% endblock %}
{% endblock %}

blog/templates/blog/blog.html
{% extends 'blog/index.html' %}

{% load static %}

{% block title %}صفحه اصلی{% endblock %}
{% block body %}
	{% block header %}{% include 'blog/header.html' %}{% endblock %}
	{% block main %}{% include 'blog/articles.html' %}{% endblock %}
{% endblock %}

blog/templates/blog/details.html
{% extends 'blog/index.html' %}

{% load static %}

{% block title %}{{ article.title }}{% endblock %}
{% block body %}
	{% block header %}{% include 'blog/header.html' %}{% endblock %}
	{% block main %}{% include 'blog/post.html' %}{% endblock %}
{% endblock %}

blog/templates/blog/header.html
<header id="header">
	<nav class="navbar navbar-expand-lg navbar-dark" id="navigationbar">
		<div class="container-fluid">
			<a class="navbar-brand" id="banner" href="{% url 'blog:home' %}">Sameet<span style='color: red;'>@</span>Moosavi</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav">
					<li class="nav-item">
					<a class="nav-link" href="{% url 'blog:blog' %}">وبلاگ</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'blog:topics' %}">تاپیک ها</a>
					</li>
				</ul>
			<div style="margin-right: auto;">
				  <a class="navbar-brand" href="http://github.com/smsameet/" title="github">
					<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 496 512" color="#FFFFFF" size="30" height="30" width="30" xmlns="http://www.w3.org/2000/svg" style="color: rgb(255, 255, 255);"><path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path></svg>
				  </a>
				<a class="navbar-brand" href="https://www.youtube.com/channel/UC_XJ4oRW4qL2Cmi7VHo9KsQ" title="youtube">
					<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 576 512" color="#EB3323" size="30" style="color: rgb(235, 51, 35);" height="30" width="30" xmlns="http://www.w3.org/2000/svg"><path d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z"></path></svg>
				</a>
			</div>
			</div>
		</div>
	</nav>
<header>

blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
	<head>
		<title>sameet | {% block title %}{% endblock %}</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
    <link rel="icon" href="media/images/myprofile.png" type="image/x-icon">
		<script type="text/javascript" src="{% static 'blog/js/bootstrap.bundle.min.js' %}"></script>
	</head>
	<body>
		{% block body %}{% endblock %}
	</body>
</html>

blog/templates/blog/main.html
<div class="container">
	<div id="main">
		<h1 style="color: #d19a66; text-align: center; margin: 30px;">نمونه کار ها </h2>
		{% for content in contents %}
			<article id="article">
				<div class="card col-sm-12 col-xl-9">
				  <div class="row g-0">
					  <div class="col-xl-4 col-lg-4 col-sm-12">
              <a href="{{ content.thumbnail_link }}"><img src="{{ content.thumbnail.url }}" class="img-fluid rounded-start" alt="..."></a>
					</div>
					<div class="col-sm-12 col-lg-8 col-xl-8">
					  <div class="card-body">
						  <h5 class="card-title">{{ content.title }}</h5>
						  <p class="card-text">{{ content.body | truncatechars:350 }}</p>
					  </div>
					</div>
				  </div>
				</div>
			</article>
		{% endfor %}
	</div>
</div>

blog/templates/blog/post.html
<div class="container">
	<div id="thumbnail">
		<img src="{{ article.thumbnail.url }}" alt="...">
	</div>
	<div id="content">
		<h1 id="ArticleTitle">{{ article.title }}</h1>
		<div id="ArticleContent">{{ article.body | safe }}</div>
	</div>
	<div id="information">
		<p>اپدیت شده در : {{ article.created }}</p>
		<p>
			تاپیک :
			{% for topic in topics %}
				{{ topic.title }} , 
			{% endfor %}
		</p>
	</div>
</div>

blog/templates/blog/topic.html
{% extends 'blog/index.html' %}

{% load static %}

{% block title %}{{ topic.title }}{% endblock %}
{% block body %}
	{% block header %}{% include 'blog/header.html' %}{% endblock %}
	{% block main %}
		<div class="container">
			<div id="main">
				<h1 style="color: #d19a66; text-align: center; margin: 30px;">مقالات</h2>
				{% for article in topic.articles.all %}
					<article id="article">
						<div class="card col-sm-12 col-xl-9">
							<div class="row g-0">
								<div class="article-tumbnail col-xl-4 col-lg-4 col-sm-12 ">
									<a href="{% url 'blog:details' article.slug %}"><img src="{{ article.thumbnail.url }}" class="img-fluid rounded-start" alt="..."></a>
								</div>
								<div id="card-body" class="col-sm-12 col-lg-8 col-xl-8">
									<div class="card-body">
										<a href="{% url 'blog:details' article.slug %}"><h2 class="card-title">{{ article.title }}</h2></a>
										<p>{{ article.created }}</p>
										<p>
											تاپیک :
											{% for topic in topics %}
												{{ topic.title }} , 
											{% endfor %}
										</p>
									</div>
								</div>
							</div>
						</div>
					</article>
				{% endfor %}
			</div>
		</div>
	{% endblock %}
{% endblock %}

blog/templates/blog/topics.html
{% extends 'blog/index.html' %}

{% load static %}

{% block title %}صفحه اصلی {% endblock %}
{% block body %}
	{% block header %}{% include 'blog/header.html' %}{% endblock %}
	{% block main %}
		<div class="container">
			<div id="main" class="col-md-12 col-sm-12">
				<h1 style="color: #d19a66; text-align: center; margin: 30px;">تاپیک ها</h1>
				<div id="tags" class="col-md-10" style="margin: auto;">
					{% for topic in topics %}
						<a href="{{ topic.slug }}">
							<h2 class="topics">{{ topic.title }}</h2>
						</a>
					{% endfor %}
				</div>
			</div>
		</div>
	{% endblock %}
{% endblock %}